### ISSUE TITLE
Minimum Viable Product Req.

### ISSUE THREAD

**Issue by pope410211** [melrodbos/TIY-Upvote#16]
### MVP
- [x] [Anyone can view a list of questions.](https://github.com/melrodbos/TIY-Upvote/issues/18)
- [x] [Anyone can view a specific question/answer.](https://github.com/melrodbos/TIY-Upvote/issues/19)
- [x] [Anyone can login with _GitHub_.](https://github.com/melrodbos/TIY-Upvote/issues/20)
- [ ] [A member can ask a new question.](https://github.com/melrodbos/TIY-Upvote/issues/21)
- [ ] [A member can answer a question.](https://github.com/melrodbos/TIY-Upvote/issues/22)
- [ ] A member who asked the question can select the answer.

**Comment by pope410211** [comment]
[MAIN PLAN](https://github.com/melrodbos/TIY-Upvote/issues/3)
