### ISSUE TITLE
Master Plan

### ISSUE THREAD

**Issue by BFGriffith** [melrodbos/TIY-Upvote#3]
# TIY-Upvote
## class checklist for MVP + stretch-goals:
- **Minimum Viable Product**
  - [x] [**Anyone can view the list of Questions...**](https://github.com/melrodbos/TIY-Upvote/issues/18) — **estimate** — _assignee_ (tonight?)
  - [x] [**Anyone can view a specific Question...**](https://github.com/melrodbos/TIY-Upvote/issues/19) — **estimate** — _assignee_
  - [ ] [**Anyone can login with Github...**](https://github.com/melrodbos/TIY-Upvote/issues/20) — **estimate** — _assignee_
  - [x] [**A Member can ask a Question...**](https://github.com/melrodbos/TIY-Upvote/issues/21) — **estimate** — _assignee_
  - [ ] [**A Member can provide an Answer...**](https://github.com/melrodbos/TIY-Upvote/issues/22) — **estimate** — _assignee_
  - [ ] **A Member who asked a Question can select an Answer...** — **estimate** — _assignee_
  - **BEAST MODE: Stretch Goals**
    - [ ] **A Member can vote on an Answer...**
    - [ ] **A Member can vote on a Question...**
    - [ ] **A Member can comment on Questions...**
    - [ ] **A Member can comment on Answers...**
  - **NIGHTMARE MODE**
    - [ ] **Anyone can sort Questions...**
      - by number of votes
      - by most recent
      - by unanswered

---
### GENERAL plans for separation of concerns:
- MainController — **medium** — _Michael and Kim_
### MINIMUM VIABLE PRODUCT priorities:
- **All Your Firebase Are Belong To Us...** — **medium** — _assignee_ (tonight?)
- **Anyone can view a list of Questions...**
  - `feature/question-list-scaffolding` — **medium** — _Ben and Nick_
- `feature/question-list-dummy-data` — **estimate** — _assignee_
- `feature/question-list-live-data` — **estimate** — _assignee_
- **Anyone can view a Question...** — **estimate** — _assignee_
- **Anyone can view the Answers...** — **estimate** — _assignee_
- **A Member can add a Question...** — **estimate** — _assignee_
- **A Member can vote on a Question...** — **estimate** — _assignee_
- **A Member can vote on an Answer...** — **estimate** — _assignee_
  - **A Member who asked a Question can accept an Answer...** — **estimate** — _assignee_
- `feature/login-scaffolding` — **estimate** — _assignee_
- `feature/login-dummy-data` — **estimate** — _assignee_
- `feature/login-live-data` — **estimate** — _assignee_
- `feature/login-service` — **estimate** — _assignee_
### STRETCH-GOALS:
- **_BEAST MODE_ Anyone can login with Github...**

---
## **Features**
- [ ] **All Your Firebase Are Belong To Us...** — **estimate** — _assignee_
  - [x] Created branch `feature/getting-started`
  - [x] Defined module `tiy-upvote`...
  - [ ] Defined `MainController`...
  - [x] Attached `tiy-upvote` to `<html>`...
  - [ ] Attached `MainController as app` to `<body>`...
  - [x] Included `Restangular` on the page...
  - [x] Added `restangular` as a dependency to `tiy-upvote`
  - [ ] Added `Restangular` as a dependency to `MainController`...
  - [ ] Configured `Restangular` to use _your_ Firebase...
  - [ ] Pushed data into _your_ Firebase with `Restangular.one(...).put()`
  - [ ] Fetched data from _your_ Firebase with `Restangular.one(...).get()`
  - [ ] Commented that code...
  - [ ] Merged that branch...
- [ ] _...Are Belong To Us_*
  - [ ] Created _Milestones_ for User Stories
  - [ ] **Anyone can view a list of Questions...**
    - [x] [`feature/question-list-scaffolding`](https://github.com/melrodbos/TIY-Upvote/issues/6)
      - [x] created Home Page `index.html`
      - [x] added route `questions`
      - [x] wrote MFg HTML for question list
      - [x] added dummy text and numbers
      - [ ] wrote Sass with Bootstrap
    - [ ] `feature/question-list-dummy-data` — **estimate** — _assignee_
      - [x] created dummy data for `questions`
      - [x] attached dummy data to controller
      - [x] used `ng-repeat` to generate list
      - [ ] used `{{expressions}}` with dummy data
    - [ ] `feature/question-list-live-data` — **estimate** — _assignee_
      - [ ] created real data in Firebase (manually)
      - [ ] fetched data from Firebase with `Restangular`
      - [ ] attached data to controller
  - [ ] **Anyone can view a Question...**
    - [x] `feature/question-detail-scaffolding`
    - [x] `feature/question-detail-dummy-data`
    - [ ] `feature/question-detail-live-data`
  - [ ] *_Anyone can view the Answers..._
    - [ ] `feature/answer-list-scaffolding`
    - [ ] `feature/answer-list-dummy-data`
    - [ ] `feature/answer-list-live-data`
  - [ ] *_A Member can add a Question..._
    - [ ] `feature/question-add-scaffolding`
      - [ ] created `views/questions-add.html`
      - [ ] defined route `questions/add`
      - [ ] wrote MFg HTML (`<form>`) to add question
      - [ ] added dummy text and numbers (where appropriate)
      - [ ] wrote Sass with Bootstrap
    - [ ] `feature/question-add-dummy-data`
      - [ ] form processing (simply)
    - [ ] `feature/question-add-live-data`
      - [ ] data persistence (simply)
  - [ ] **A Member can add an Answer...**
    - [ ] `feature/answer-add-scaffolding`
    - [ ] `feature/answer-add-dummy-data`
    - [ ] `feature/answer-add-live-data`
  - [ ] *_A Member can vote on a Question..._
    - [ ] `feature/question-vote-scaffolding` — **estimate** — _assignee_
      - [ ] wrote MFg HTML and Sass for voting interface
      - [ ] don't forget hover and active states!
    - [ ] `feature/question-vote-dummy-data`
      - [ ] added and attached dummy data (up-vote, down-vote, no-vote, `nVotes`)
      - [ ] need more styles? of course ya do!
    - [ ] `feature/question-vote-interface` — **estimate** — _assignee_
      - [ ] wired up voting interface:
        - no-vote to up-vote: set `.active`, update `nVotes`
        - up-vote to no-vote: remove `.active`, update `nVotes`
        - no-vote to dn-vote: set `.active`, update `nVotes`
        - dn-vote to no-vote: remove `.active`, update `nVotes`
      - [ ] **BEAST MODE** refactor to service object?
    - [ ] `feature/question-vote-live-data` — **estimate** — _assignee_
      - [ ] fetch `votes` when `question` is loaded
      - [ ] populate interface with `votes`
      - [ ] update `question` data when `votes` added / changed
      - [ ] **BEAST MODE** display vote for current user?
  - **A Member can vote on an Answer...**
  - **A Member who asked a Question can accept an Answer...**
  - **_BEAST MODE_ Anyone can login with Github...**
    - [ ] `feature/login-scaffolding` — **estimate** — _assignee_
      - [ ] created `views/login.html`
      - [ ] defined route `login`
      - [ ] configured OAuth dance for Firebase and Github
      - [x] `bower install firebase`
      - [x] configure `Firebase` in `MainController`
    - [ ] `feature/login-dummy-data` — **estimate** — _assignee_
      - [ ] wrote MF'g HTML and Sass for `views/login.html`
      - [ ] wired up "Login with Github" button to `Firebase.authWithOAuthPopup`
      - [ ] confirm user login with:
        - [ ] tracer bullet
        - [ ] display "Logout" button
        - [ ] display username / avatar
        - [ ] redirect to `questions` route
    - `feature/login-live-data` — **estimate** — _assignee_
      - [ ] prevented access to any route until authenticated
      - [ ] recorded username for authenticated actions:
        - [ ] add a Question
        - [ ] add an Answer
        - [ ] vote on Question
        - [ ] vote on Answer
        - [ ] accept Answer for Question
        - [ ] unaccept Answer for Question
    - `feature/login-service` — **estimate** — _assignee_
      - [ ] refactor to named service: `Auth`
        - `Auth.login()`
          - `@param none`
          - `@return Promise`
        - `Auth.logout()`
          - `@param none`
          - `@return Promise`
        - `Auth.isAuthd()`
          - `@param none`
          - `@return Boolean`
        - `Auth.getAuth()`
          - `@param none`
          - `@return Object from Firebase.getAuth()`

---
## **Team Contract**
- Run standup meeting at the beginning of each group session
- Review completed features vs list of planned features to constantly evaluate scope
- Maintain main issue with all planned features
- Require team members to create an issue for each feature they do, link to feature PR
- Require team members to include checkboxes in the PR description when opening for a feature
- All checkboxes should be checked before merging a PR and close open feature issue
- Mark feature as complete in issue#1 or whatever the first project issue is with list of all planned features
- Before merging any feature, team member working said feature needs review by another team member
- Reviewing team member gives thumbs up on pull request saying feature is reviewed
- Team working feature sends slack message to entire team advising of merge, all other team members must git pull origin develop

**Team Lead Responsibilities**
- Run standup meeting at the beginning of each group session
- Review completed features versus list of planned features to be mindful of scope
- Maintain main issue with all planned features (marking off completed if needed)

**Team Member Responsibilities**
- Create an issue for each feature with a link to feature PR
- Include checkboxes in the PR description when opening for a feature
- All checkboxes should be checked or notations made and feature issue should be closed before merging a PR
- Before merging any feature, team member feature needs review by another team member (partner + team lead)
- Reviewing team member gives thumbs up on pull request saying feature is reviewed
- Mark feature as complete in issue#1 or whatever the first project issue is with list of all planned features
- Merge feature with GitFlow
- Team-member working on feature sends slack message to entire team advising of merge, so that all other team members must `git pull origin develop`

**Naming Conventions**
- Use underscores instead of dashes? (easier to highlight entire string using double-click)

**Comment by pope410211** [comment]
https://github.com/melrodbos/TIY-Upvote/issues/6

**Comment by melrodbos** [comment]
- Yak-Shaving #1
- Planning #2 
- HTML/ Sass #3
- Angular #4

![plan_monday](https://cloud.githubusercontent.com/assets/12171924/8444305/37d5a206-1f5d-11e5-9c9e-9cfa171bf1d5.jpg)

**Comment by melrodbos** [comment]
- Dummy Data #8
- 404.html #7

![pages_monday](https://cloud.githubusercontent.com/assets/12171924/8444309/42850fd4-1f5d-11e5-8dc8-8219e879d98a.jpg)

**Comment by melrodbos** [comment]
What we did yesterday: 
- JS setup, identified controllers, directives...
- Skeletal HTML for main three views
- Dummy data json files

What we will be working on today:
- firebase
- connecting page views with JS
- basic styling

Getting on our way: (Blockers)
- [x] Linking html documents to main.js
- [ ] Fixing sass (
- [x] Firebase setup
